name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.11.4"]
        poetry-version: ["1.5.1"]
      fail-fast: false
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup
        with:
          python-version: ${{ matrix.python-version }}
          poetry-version: ${{ matrix.poetry-version }}

      - name: Black - code formatting
        continue-on-error: true
        shell: bash
        run: poetry run black --check navel tests

      - name: Mypy - type checking
        continue-on-error: true
        shell: bash
        run: poetry run mypy navel

      - name: PyLint - linter
        continue-on-error: true
        shell: bash
        run: poetry run pylint navel
